Miscellaneous New and Noteworthy fixes for 4.27
eclipse-platform/eclipse.platform.common pull request #141
Opened 2023-04-17 14:30 UTC by alshamams

-fix incorrect versioning
-load missing images (End user reported)
-fix incorrect html tagging

/cc @lshanmug

2023-04-18 14:31 UTC, lshanmug requested changes

2023-04-18 14:31 UTC, lshanmug commented on bundles/org.eclipse.jdt.doc.user/whatsNew/jdt_whatsnew.html
> +	<li><a href="#JavaCompiler" target="_blank">Java Compiler</a></li>
target="_blank" is added when the link can't open in the same frame and has to be opened in a new tab. It's not required in these places. Any reason it's added?

2023-04-18 14:31 UTC, lshanmug commented on bundles/org.eclipse.jdt.doc.user/whatsNew/jdt_whatsnew.html
> -     <p>For details on the inline <b>@return</b> tag, see: <a href="https://docs.oracle.com/en/java/javase/19/docs/specs/javadoc/doc-comment-spec.html#return" target="_blank">Javadoc Comment Spec</a>
target="_blank" is required, should not be removed.

2023-04-18 14:31 UTC, lshanmug commented on bundles/org.eclipse.jdt.doc.user/whatsNew/jdt_whatsnew.html
> -      via <a href="https://download.eclipse.org/eclipse/updates/latest/" target="_blank">https://download.eclipse.org/eclipse/updates/latest/</a>
target="_blank" is required, should not be removed.

2023-04-18 14:31 UTC, lshanmug commented on bundles/org.eclipse.pde.doc.user/whatsNew/pde_whatsnew.html
> +	<li><a href="#GeneralUpdates" target="_blank">General Updates</a></li>
target="_blank" not required

2023-04-18 14:31 UTC, lshanmug commented on bundles/org.eclipse.platform.doc.isv/whatsNew/platform_isv_whatsnew.html
> +  <li><a href="#Platform" target="_blank">Platform Changes</a></li>
target="_blank" not required

2023-04-18 14:31 UTC, lshanmug commented on bundles/org.eclipse.platform.doc.isv/whatsNew/platform_isv_whatsnew.html
> +<a href="../../org.eclipse.platform.doc.user/whatsNew/platform_whatsnew.html" target="_blank">What's New</a>
target="_blank" not required

2023-04-18 17:32 UTC, alshamams commented
@lshanmug 
I have made the required changes. Kindly review and let me know.

2023-04-20 04:15 UTC, alshamams commented
@lshanmug 
Kindly look through and let me know if there are any other edits.

2023-04-20 06:52 UTC, lshanmug approved these changes

2023-04-20 06:58 UTC, lshanmug requested changes

2023-04-20 06:58 UTC, lshanmug commented on bundles/org.eclipse.pde.doc.user/topics_WhatsNew.xml
> -
Please don't change unrelated parts in the PR. Please review the diff in Eclipse before updating the PR.

2023-04-20 06:58 UTC, lshanmug commented on bundles/org.eclipse.pde.doc.user/whatsNew/pde_whatsnew.html
> -</html>
Please don't change unrelated parts in the PR

2023-04-20 16:05 UTC, lshanmug approved these changes

2023-04-20 16:06 UTC, merged

2023-05-17 08:44 UTC, MohananRahul commented
Tracked #995